{% set name = "nr.parsing.date" %}
{% set version = "1.0.3" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/nr.parsing.date-{{ version }}.tar.gz
  sha256: dbd4fe953c2846a8d2e454c760049e262f302f43e5193705dc0abb794af6b3d7

build:
  number: 2
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python {{ python_min }}
  run:
    - dataclasses >=0.6.0,<1.0.0
    - nr.utils.re >=0.2.0,<1.0.0
    - dataclasses >=0.6.0,<1.0.0
    - python >={{ python_min }},<4.0

test:
  imports:
    - nr
    - nr.parsing.date
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://git.niklasrosenstein.com/NiklasRosenstein/nr
  summary: A fast, regular-expression based library for parsing dates, plus support for ISO 8601 durations.
  license: MIT
  license_file: LICENSE.txt

extra:
  recipe-maintainers:
    - NiklasRosenstein
